### ISSUE TITLE
When attempting to mute a user, if the time is specified like "7 years" (as opposed to something like "7y") Cliptok deletes the message but does not mute the user

### ISSUE THREAD

**Issue by FloatingMilkshake** [Erisa/Cliptok#21] opened 2021-02-09 13:47 UTC
Title pretty much says it all. If you attempt to mute a user like this: `!mute @FloatingMilkshake 7 years test`, Cliptok deletes the message but does not mute the user. But this works as expected: `!mute @FloatingMilkshake 7y test`. I would assume the former would work based on the arguments for `!mute` (`mute <targetMember> [timeAndReason...]`), perhaps it's not supposed to though.

[Here's a screen recording of the issue.](https://streamable.com/llq74q)

**Comment by Erisa** [comment] 2021-02-09 13:58
Keep in mind the input is very specifically tuned to the 5h/1d/5w/7y/etc format, supplying `7 years` isnt expected to work and as you discovered confuses it a lot. 

If the code was working correctly it would use `7 years test` as the full reason and apply a permanent mute, due to the fixed format of the argument this would be the intended behaviour.

The bug here is that it's not actually doing anything to the user, to properly reproduce that I'll need to know what roles they have and I'll try it out sometime later.
Making the precarious system accept something like `7 years` is certainly possible if its requested enough, the only reason I didn't is to avoid a large amount of work on something that may never be needed since everyone uses the existing syntax. What definitely needs work is documentation about how these commands are supposed to be used.

**Comment by FloatingMilkshake** [comment] 2021-02-09 14:03
Oh okay! I assumed it would accept `7 years`. My bad then. But yeah, since `7 years` isn't accepted as a proper time format it would apply a perma-mute with the reason `7 years test`...I think I've seen it do that before, guess I just forgot that the `7 years` format isn't accepted as a time for mutes. Thanks.

**Comment by FloatingMilkshake** [comment] 2021-02-18 03:21
> The bug here is that it's not actually doing anything to the user, **to properly reproduce that I'll need to know what roles they have** and I'll try it out sometime later.

Oops, was I supposed to answer this? I'm sorry, I totally missed it. Not sure how roles would affect this but just tested, the bug happens when trying to mute a user with no roles, a user with the Tier 1 role, and a user with the Nitro Boosters role. Didn't test any other role combinations as I can't manipulate roles and didn't want to bug Kirby, also not sure if having any other roles would affect this anyway but you know more about it than I do.

**Comment by Erisa** [comment] 2021-05-28 19:55
It seems this was fixed in 8de8243897034a829378dec3acc50becdf31e8b7

**Closed by Erisa** 2021-05-28 19:55 UTC
Labels: bug
