### ISSUE TITLE
Bug: Automod filter checks sometimes stop working

### ISSUE THREAD

**Issue by Erisa** [Erisa/Cliptok#219] opened 2024-08-19 11:28 UTC
https://discord.com/channels/150662382874525696/793285213823172628/1275050697758478371

**Comment by FloatingMilkshake** [comment] 2024-09-09 15:09
This hasn't come up again, so I'm going to close this for now. Will reopen if it becomes a problem again in the future.

From what I remember about this, on dev I would see the bot randomly stop processing AutoMod-blocked messages—I was never able to reproduce this again.

On prod we found that the bot was missing the Manage Server permission, so it would miss *all* AutoMod events. Discord's developer docs mention this [here](https://discord.com/developers/docs/topics/gateway-events#auto-moderation), and mod context is here: https://discord.com/channels/150662382874525696/793285213823172628/1276749034547056671. So far the bot has successfully processed all AutoMod events since granting that permission ¯\\\_(ツ)_/¯

**Closed by FloatingMilkshake** 2024-09-09 15:09 UTC
Labels: bug
